# Generated by Django 5.2.14 on 2026-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bookingrequest_foodorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
