# Generated by Django 5.2.14 on 2026-05-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bookingrequest_num_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='verification_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
